#include "dados.h"

const vector<string> verbos = {
    "Comprar",
    "Vender",
    "Arrumar",
    "Consertar",
    "Terminar",
    "Cadastrar",
    "Confirmar",
    "Apagar",
    "Deletar",
    "Criar",
    "Fazer",
    "Atualizar",
    "Completar",
    "Pagar",
    "Preparar",
    "Finalizar",
    "Marcar",
    "Limpar",
    "Construir",
    "Sacar",
    "Distribuir",
    "Ajudar",
    "Organizar"
};

const vector<string> nomes = {
    "bug",
    "produto",
    "registro",
    "documento",
    "relatório",
    "pesquisa",
    "problema",
    "erro",
    "conta",
    "dívida",
    "currículo",
    "tarefa",
    "atividade",
    "exercício",
    "reunião",
    "reserva",
    "sujeira",
    "lixo",
    "salário",
    "pagamento",
    "mesada",
    "aula",
    "apresentação"
};

const vector<string> locais {
    "do carro",
    "do projeto",
    "da loja",
    "da faculdade",
    "do trabalho",
    "do estágio",
    "do jardim",
    "da fazenda",
    "da casa",
    "do quarto",
    "do emprego",
    "dos alunos",
    "dos estudantes",
    "dos professores",
    "do diretor",
    "dos funcionários",
    "dos empregados",
    "dos dados",
    "do auditório",
    "da piscina",
    "do quintal",
    "do patrão",
    "do chefe",
    "do filho",
    "da filha",
    "do pai",
    "da mãe",
    "do tio",
    "da tia",
    "da mesa",
    "do computador",
    "da cadeira",
    "da máquina",
    "do celular",
    "do telefone"
};

const int N_VERBOS = verbos.size();
const int N_NOMES = nomes.size();
const int N_LOCAIS = locais.size();
